export const ACTION_GALLERY_REQUEST = 'ACTION_GALLERY_REQUEST'

export const ACTION_GALLERY_REQUEST_SUCCESS = 'ACTION_GALLERY_REQUEST_SUCCESS'

export const ACTION_GALLERY_REQUEST_FAIL = 'ACTION_GALLERY_REQUEST_FAIL'

export const ACTION_GALLERY_SET_CURRENT_PICTURE = 'ACTION_GALLERY_SET_CURRENT_PICTURE'