export const ACTION_GALLERY_REQUEST = 'ACTION_GALLERY_REQUEST'

export const ACTION_GALLERY_REQUEST_SUCCESS = 'ACTION_GALLERY_REQUEST_SUCCESS'

export const ACTION_GALLERY_REQUEST_FAIL = 'ACTION_GALLERY_REQUEST_FAIL'